dist: xenial
language: python
cache: pip
python:
  - '3.7'
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coveralls pytest-cov
script:
  - pytest --disable-pytest-warnings --doctest-modules --doctest-report ndiff jobs tests
after_success:
  - coveralls
