dist: xenial
services:
  - postgresql
addons:
  postgresql: "11.0"
language: python
cache: pip
python:
  - '3.7'
env:
  - BOTO_CONFIG=/dev/null AWS_DEFAULT_REGION=eu-central-1 AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coveralls pytest-cov
before_script:
  - psql -c 'CREATE DATABASE jobdb;' -U postgres
script:
  - pytest --disable-pytest-warnings --doctest-modules --doctest-report ndiff jobs tests
after_success:
  - coveralls
