language: python

cache: pip

python:
  - '2.7'

install:
  - pip install -r requirements.txt
  - pip install coveralls

scripts:
  - pytest --doctest-modules --doctest-report ndiff jobs

after_success:
  - coveralls
