service: spiders

package:
  exclude:
    - .cache/**
    - .idea/**
    - .pytest_cache/**
    - .scrapy/**
    - .vscode/**
    - .coverage
    - tests/**
    - .pep8
    - .python-version
    - .pyup.yml
    - .travis.yml
    - LICENSE
    - README.rst
    - requirements.txt
    - test_requirements.txt
    - setup.cfg

provider:
  name: aws
  runtime: python3.7
  timeout: 30

functions:
  tvinna:
    handler: lambda.run
    environment:
      SCRAPY_SPIDER: tvinna
  mbl:
    handler: lambda.run
    environment:
      SCRAPY_SPIDER: mbl
  alfred:
    handler: lambda.run
    environment:
      SCRAPY_SPIDER: alfred

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    useDownloadCache: true
    slim: true
