service: spiders

package:
  exclude:
    - .cache/**
    - .idea/**
    - .pytest_cache/**
    - .scrapy/**
    - .vscode/**
    - .coverage
    - tests/**
    - .pep8
    - .python-version
    - .pyup.yml
    - .travis.yml
    - LICENSE
    - README.rst
    - requirements.txt
    - test_requirements.txt
    - setup.cfg

provider:
  name: aws
  runtime: python3.7
  timeout: 30
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
      Resource: "*"

functions:
  tvinna:
    handler: handler.run
    environment:
      SCRAPY_SPIDER: tvinna
    events:
      - schedule: rate(30 minutes)
  mbl:
    handler: handler.run
    environment:
      SCRAPY_SPIDER: mbl
    events:
      - schedule: rate(30 minutes)
  alfred:
    handler: handler.run
    environment:
      SCRAPY_SPIDER: alfred
    events:
      - schedule: rate(30 minutes)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    useDownloadCache: true
    slim: true
